# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SuperHeroes' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for SuperHeroes

  target 'SuperHeroes-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SuperHeroesTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'SuperHeroes-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for SuperHeroes-tvOS

  target 'SuperHeroes-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
